// ═══════════════════════════════════════════════════════════
// SEO CONTENT UTILITIES
// Embedded content for Vercel deployment
// Run: pnpm tsx scripts/generate-seo-pages.ts to regenerate
// ═══════════════════════════════════════════════════════════

export interface SEOPage {
  id?: string;
  slug: string;
  title: string;
  meta_description: string;
  quick_answer: string[];
  content: string;
  asset_type: string;
  internal_links: string[];
  schema_type: string;
  expert: string;
  secondary_expert?: string;
  generated_at: string;
  has_neoball_cta: boolean;
  knowledge_graph?: {
    type?: string;
    parent_pillar?: string;
    spokes?: string[];
    cluster?: string;
    total_volume?: number;
    total_cluster_volume?: number;
    consolidates?: string[];
    cross_links?: string[];
    hierarchy?: Record<string, unknown>;
  };
  visual_asset?: {
    data?: Record<string, unknown>;
  };
}

// ─────────────────────────────────────────────────────────────
// EXPERT DATA
// ─────────────────────────────────────────────────────────────

export const EXPERTS = {
  "adam-harrington": {
    name: "Adam Harrington",
    title: "NBA Skills Coach & Founder, YP Basketball Foundations",
    icon: "🏀",
    bio: "20+ years training NBA players including Kevin Durant, Devin Booker, and Bradley Beal. Creator of the R3 Methodology.",
  },
  "james-scott": {
    name: "James Scott",
    title: "Co-founder & Inventor, NeoBall",
    icon: "⚡",
    bio: "Sports equipment innovator. Created the world's first silent basketball for home training.",
  },
} as const;

// ─────────────────────────────────────────────────────────────
// LOAD EMBEDDED PAGES DATA
// Generated by: scripts/generate-seo-pages.ts
// ─────────────────────────────────────────────────────────────

import { SEO_PAGES_DATA } from "./seo-pages-data";

export function loadAllPages(): SEOPage[] {
  return SEO_PAGES_DATA;
}

// ─────────────────────────────────────────────────────────────
// UTILITY FUNCTIONS
// ─────────────────────────────────────────────────────────────

/**
 * Get a page by its slug path
 * @param slugPath - e.g., ["basketball", "silent-training"] or ["basketball", "home-training", "indoor-drills"]
 */
export function getPageBySlug(slugPath: string[]): SEOPage | undefined {
  const fullSlug = "/" + slugPath.join("/");
  return SEO_PAGES_DATA.find((page) => page.slug === fullSlug);
}

/**
 * Get all pages for static generation
 */
export function getAllSEOSlugs(): string[][] {
  return SEO_PAGES_DATA.map((page) => {
    // Remove leading slash and split
    const parts = page.slug.slice(1).split("/");
    return parts;
  });
}

/**
 * Get pillar pages only
 */
export function getPillarPages(): SEOPage[] {
  return SEO_PAGES_DATA.filter((page) => page.knowledge_graph?.type === "pillar");
}

/**
 * Get spoke pages for a pillar
 */
export function getSpokesForPillar(pillarSlug: string): SEOPage[] {
  // Extract the pillar key from the slug (e.g., "home-training" from "/basketball/home-training")
  const pillarKey = pillarSlug.split("/").pop() || "";
  return SEO_PAGES_DATA.filter((page) => {
    const parentPillar = page.knowledge_graph?.parent_pillar;
    // Match "home-training-guide" -> "home-training" or direct match
    return parentPillar === pillarKey || parentPillar === `${pillarKey}-guide`;
  });
}

/**
 * Get expert info
 */
export function getExpert(expertId: string) {
  return EXPERTS[expertId as keyof typeof EXPERTS];
}

/**
 * Convert markdown content to basic HTML
 */
export function markdownToHtml(content: string): string {
  let html = content;

  // Headers (process from h3 to h2 to avoid partial matches)
  html = html.replace(/^### (.*$)/gim, '<h3 class="text-xl font-bebas tracking-wider mt-8 mb-4 text-white">$1</h3>');
  html = html.replace(/^## (.*$)/gim, '<h2 class="text-2xl md:text-3xl font-bebas tracking-wider mt-12 mb-6 text-white">$1</h2>');

  // Bold
  html = html.replace(/\*\*(.*?)\*\*/g, '<strong class="font-semibold text-white">$1</strong>');

  // Italic
  html = html.replace(/\*(.*?)\*/g, '<em>$1</em>');

  // Links
  html = html.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2" class="text-accent-primary hover:underline">$1</a>');

  // Tables - match header row, separator row, and body rows
  html = html.replace(/\|(.+)\|\n\|[-| :]+\|\n((?:\|.+\|\n?)+)/g, (match, header, body) => {
    const headerCells = header.split("|").filter(Boolean).map((cell: string) =>
      `<th class="px-4 py-2 border border-white/10 text-left font-semibold text-white">${cell.trim()}</th>`
    ).join("");

    const rows = body.trim().split("\n").map((row: string) => {
      const cells = row.split("|").filter(Boolean).map((cell: string) =>
        `<td class="px-4 py-2 border border-white/10 text-text-secondary">${cell.trim()}</td>`
      ).join("");
      return `<tr>${cells}</tr>`;
    }).join("");

    return `<div class="overflow-x-auto mb-6"><table class="w-full border-collapse"><thead><tr>${headerCells}</tr></thead><tbody>${rows}</tbody></table></div>`;
  });

  // Unordered lists (handle consecutive lines)
  html = html.replace(/(^- .+$\n?)+/gm, (match) => {
    const items = match.trim().split("\n").map(line => {
      const text = line.replace(/^- /, "");
      return `<li class="ml-6 mb-2 text-text-secondary list-disc">${text}</li>`;
    }).join("");
    return `<ul class="mb-6">${items}</ul>`;
  });

  // Numbered lists
  html = html.replace(/(^\d+\. .+$\n?)+/gm, (match) => {
    const items = match.trim().split("\n").map(line => {
      const text = line.replace(/^\d+\. /, "");
      return `<li class="ml-6 mb-2 text-text-secondary">${text}</li>`;
    }).join("");
    return `<ol class="mb-6 list-decimal">${items}</ol>`;
  });

  // Paragraphs - wrap lines that aren't already HTML
  html = html.split("\n\n").map(block => {
    const trimmed = block.trim();
    if (trimmed && !trimmed.startsWith("<") && !trimmed.startsWith("#") && !trimmed.startsWith("|")) {
      return `<p class="mb-4 text-text-secondary leading-relaxed">${trimmed}</p>`;
    }
    return trimmed;
  }).join("\n");

  return html;
}
