#!/usr/bin/env tsx
// ═══════════════════════════════════════════════════════════
// GENERATE SEO PAGES DATA
// Reads JSON from machine-sprint output and creates TypeScript
// Run: pnpm tsx scripts/generate-seo-pages.ts
// ═══════════════════════════════════════════════════════════

import fs from "fs";
import path from "path";

const PAGES_DIR = path.join(__dirname, "../../../tools/machine-sprint/output/pages");
const OUTPUT_FILE = path.join(__dirname, "../src/lib/generated-seo-pages.ts");

// Read all JSON files from the pages directory
function getPageFiles(): string[] {
  if (!fs.existsSync(PAGES_DIR)) return [];
  return fs.readdirSync(PAGES_DIR)
    .filter(f => f.endsWith('.json'))
    .sort();
}

interface SEOPage {
  slug: string;
  title: string;
  meta_description: string;
  quick_answer: string[];
  content: string;
  asset_type: string;
  internal_links: string[];
  schema_type: string;
  expert: string;
  secondary_expert?: string;
  generated_at: string;
  has_neoball_cta: boolean;
  knowledge_graph: Record<string, unknown>;
}

function main() {
  console.log("📖 Reading SEO page JSON files...");

  const PAGE_FILES = getPageFiles();
  console.log(`   Found ${PAGE_FILES.length} JSON files`);

  const pages: SEOPage[] = [];

  for (const file of PAGE_FILES) {
    const filePath = path.join(PAGES_DIR, file);
    try {
      const content = fs.readFileSync(filePath, "utf-8");
      const page = JSON.parse(content) as SEOPage;
      // Ensure slug starts with /
      if (!page.slug.startsWith('/')) {
        page.slug = '/' + page.slug;
      }
      pages.push(page);
      console.log(`  ✓ ${file} -> ${page.slug}`);
    } catch (e) {
      console.log(`  ✗ ${file} (error: ${e})`);
    }
  }

  console.log(`\n📝 Generating TypeScript file with ${pages.length} pages...`);

  const tsContent = `// ═══════════════════════════════════════════════════════════
// AUTO-GENERATED SEO PAGES DATA
// Generated by: pnpm tsx scripts/generate-seo-pages.ts
// Generated at: ${new Date().toISOString()}
// DO NOT EDIT MANUALLY - regenerate from machine-sprint output
// ═══════════════════════════════════════════════════════════

import type { SEOPage } from "./seo-content";

export const GENERATED_SEO_PAGES: SEOPage[] = ${JSON.stringify(pages, null, 2)};
`;

  fs.writeFileSync(OUTPUT_FILE, tsContent);
  console.log(`✅ Generated: ${OUTPUT_FILE}`);
  console.log(`   Total pages: ${pages.length}`);
  console.log(`   Total volume: ${pages.reduce((sum, p) => sum + (p.knowledge_graph?.total_volume as number || p.knowledge_graph?.total_cluster_volume as number || 0), 0).toLocaleString()}`);
}

main();
