#!/usr/bin/env tsx
// ═══════════════════════════════════════════════════════════
// GENERATE SEO PAGES DATA
// Reads JSON from machine-sprint output and creates TypeScript
// Run: pnpm tsx scripts/generate-seo-pages.ts
// ═══════════════════════════════════════════════════════════

import fs from "fs";
import path from "path";

const PAGES_DIR = path.join(__dirname, "../../../tools/machine-sprint/output/pages");
const OUTPUT_FILE = path.join(__dirname, "../src/lib/seo-pages-data.ts");

// Files to include
const PAGE_FILES = [
  // Silent Training Cluster (11 pages)
  "pillar_silent-training-guide.json",
  "opp_silent_basketball_013.json",
  "opp_silent_basketball_014.json",
  "opp_silent_basketball_015.json",
  "opp_silent_basketball_017.json",
  "opp_silent_basketball_046.json",
  "opp_silent_basketball_050.json",
  "opp_silent_basketball_053.json",
  "opp_silent_basketball_054.json",
  "opp_silent_basketball_065.json",
  "opp_silent_basketball_066.json",
  // Home Training Cluster (7 pages)
  "pillar_home-training-guide.json",
  "opp_home_training_006.json",
  "opp_home_training_047.json",
  "opp_home_training_048.json",
  "opp_home_training_049.json",
  "opp_home_training_056.json",
  "opp_home_training_073.json",
];

interface SEOPage {
  slug: string;
  title: string;
  meta_description: string;
  quick_answer: string[];
  content: string;
  asset_type: string;
  internal_links: string[];
  schema_type: string;
  expert: string;
  secondary_expert?: string;
  generated_at: string;
  has_neoball_cta: boolean;
  knowledge_graph: Record<string, unknown>;
}

function main() {
  console.log("📖 Reading SEO page JSON files...");

  const pages: SEOPage[] = [];

  for (const file of PAGE_FILES) {
    const filePath = path.join(PAGES_DIR, file);
    if (fs.existsSync(filePath)) {
      const content = fs.readFileSync(filePath, "utf-8");
      const page = JSON.parse(content) as SEOPage;
      pages.push(page);
      console.log(`  ✓ ${file} -> ${page.slug}`);
    } else {
      console.log(`  ✗ ${file} (not found)`);
    }
  }

  console.log(`\n📝 Generating TypeScript file with ${pages.length} pages...`);

  const tsContent = `// ═══════════════════════════════════════════════════════════
// AUTO-GENERATED SEO PAGES DATA
// Generated by: scripts/generate-seo-pages.ts
// DO NOT EDIT MANUALLY
// ═══════════════════════════════════════════════════════════

import type { SEOPage } from "./seo-content";

export const SEO_PAGES_DATA: SEOPage[] = ${JSON.stringify(pages, null, 2)};
`;

  fs.writeFileSync(OUTPUT_FILE, tsContent);
  console.log(`✅ Generated: ${OUTPUT_FILE}`);
  console.log(`   Total pages: ${pages.length}`);
  console.log(`   Total volume: ${pages.reduce((sum, p) => sum + (p.knowledge_graph?.total_volume as number || p.knowledge_graph?.total_cluster_volume as number || 0), 0).toLocaleString()}`);
}

main();
